# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins
from . import _utilities
import typing
# Export this package's modules as members:
from .database import *
from .delta_stream_object import *
from .entity import *
from .get_database import *
from .get_databases import *
from .get_entities import *
from .get_entity_data import *
from .get_namespace import *
from .get_namespaces import *
from .get_object import *
from .get_objects import *
from .get_schema_registries import *
from .get_schema_registry import *
from .get_secret import *
from .get_secrets import *
from .get_store import *
from .get_stores import *
from .namespace import *
from .provider import *
from .query import *
from .schema_registry import *
from .secret import *
from .store import *
from ._inputs import *
from . import outputs

# Make subpackages available:
if typing.TYPE_CHECKING:
    import deltastream-pulumi.config as __config
    config = __config
else:
    config = _utilities.lazy_import('deltastream-pulumi.config')

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "deltastream",
  "mod": "index/database",
  "fqn": "deltastream-pulumi",
  "classes": {
   "deltastream:index/database:Database": "Database"
  }
 },
 {
  "pkg": "deltastream",
  "mod": "index/entity",
  "fqn": "deltastream-pulumi",
  "classes": {
   "deltastream:index/entity:Entity": "Entity"
  }
 },
 {
  "pkg": "deltastream",
  "mod": "index/namespace",
  "fqn": "deltastream-pulumi",
  "classes": {
   "deltastream:index/namespace:Namespace": "Namespace"
  }
 },
 {
  "pkg": "deltastream",
  "mod": "index/object",
  "fqn": "deltastream-pulumi",
  "classes": {
   "deltastream:index/object:DeltaStreamObject": "DeltaStreamObject"
  }
 },
 {
  "pkg": "deltastream",
  "mod": "index/query",
  "fqn": "deltastream-pulumi",
  "classes": {
   "deltastream:index/query:Query": "Query"
  }
 },
 {
  "pkg": "deltastream",
  "mod": "index/schemaRegistry",
  "fqn": "deltastream-pulumi",
  "classes": {
   "deltastream:index/schemaRegistry:SchemaRegistry": "SchemaRegistry"
  }
 },
 {
  "pkg": "deltastream",
  "mod": "index/secret",
  "fqn": "deltastream-pulumi",
  "classes": {
   "deltastream:index/secret:Secret": "Secret"
  }
 },
 {
  "pkg": "deltastream",
  "mod": "index/store",
  "fqn": "deltastream-pulumi",
  "classes": {
   "deltastream:index/store:Store": "Store"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "deltastream",
  "token": "pulumi:providers:deltastream",
  "fqn": "deltastream-pulumi",
  "class": "Provider"
 }
]
"""
)
