# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins
import copy
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = [
    'GetObjectResult',
    'AwaitableGetObjectResult',
    'get_object',
    'get_object_output',
]

@pulumi.output_type
class GetObjectResult:
    """
    A collection of values returned by getObject.
    """
    def __init__(__self__, created_at=None, database=None, fqn=None, id=None, name=None, namespace=None, owner=None, state=None, type=None, updated_at=None):
        if created_at and not isinstance(created_at, str):
            raise TypeError("Expected argument 'created_at' to be a str")
        pulumi.set(__self__, "created_at", created_at)
        if database and not isinstance(database, str):
            raise TypeError("Expected argument 'database' to be a str")
        pulumi.set(__self__, "database", database)
        if fqn and not isinstance(fqn, str):
            raise TypeError("Expected argument 'fqn' to be a str")
        pulumi.set(__self__, "fqn", fqn)
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)
        if name and not isinstance(name, str):
            raise TypeError("Expected argument 'name' to be a str")
        pulumi.set(__self__, "name", name)
        if namespace and not isinstance(namespace, str):
            raise TypeError("Expected argument 'namespace' to be a str")
        pulumi.set(__self__, "namespace", namespace)
        if owner and not isinstance(owner, str):
            raise TypeError("Expected argument 'owner' to be a str")
        pulumi.set(__self__, "owner", owner)
        if state and not isinstance(state, str):
            raise TypeError("Expected argument 'state' to be a str")
        pulumi.set(__self__, "state", state)
        if type and not isinstance(type, str):
            raise TypeError("Expected argument 'type' to be a str")
        pulumi.set(__self__, "type", type)
        if updated_at and not isinstance(updated_at, str):
            raise TypeError("Expected argument 'updated_at' to be a str")
        pulumi.set(__self__, "updated_at", updated_at)

    @property
    @pulumi.getter(name="createdAt")
    def created_at(self) -> builtins.str:
        """
        Creation date of the object
        """
        return pulumi.get(self, "created_at")

    @property
    @pulumi.getter
    def database(self) -> builtins.str:
        """
        Name of the Database
        """
        return pulumi.get(self, "database")

    @property
    @pulumi.getter
    def fqn(self) -> builtins.str:
        """
        Fully qualified name of the Object
        """
        return pulumi.get(self, "fqn")

    @property
    @pulumi.getter
    def id(self) -> builtins.str:
        """
        The provider-assigned unique ID for this managed resource.
        """
        return pulumi.get(self, "id")

    @property
    @pulumi.getter
    def name(self) -> builtins.str:
        """
        Name of the Object
        """
        return pulumi.get(self, "name")

    @property
    @pulumi.getter
    def namespace(self) -> builtins.str:
        """
        Name of the Namespace
        """
        return pulumi.get(self, "namespace")

    @property
    @pulumi.getter
    def owner(self) -> builtins.str:
        """
        Owning role of the object
        """
        return pulumi.get(self, "owner")

    @property
    @pulumi.getter
    def state(self) -> builtins.str:
        """
        State of the Object
        """
        return pulumi.get(self, "state")

    @property
    @pulumi.getter
    def type(self) -> builtins.str:
        """
        Type of the Object
        """
        return pulumi.get(self, "type")

    @property
    @pulumi.getter(name="updatedAt")
    def updated_at(self) -> builtins.str:
        """
        Last update date of the object
        """
        return pulumi.get(self, "updated_at")


class AwaitableGetObjectResult(GetObjectResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetObjectResult(
            created_at=self.created_at,
            database=self.database,
            fqn=self.fqn,
            id=self.id,
            name=self.name,
            namespace=self.namespace,
            owner=self.owner,
            state=self.state,
            type=self.type,
            updated_at=self.updated_at)


def get_object(database: Optional[builtins.str] = None,
               name: Optional[builtins.str] = None,
               namespace: Optional[builtins.str] = None,
               opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetObjectResult:
    """
    Object resource


    :param builtins.str database: Name of the Database
    :param builtins.str name: Name of the Object
    :param builtins.str namespace: Name of the Namespace
    """
    __args__ = dict()
    __args__['database'] = database
    __args__['name'] = name
    __args__['namespace'] = namespace
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('deltastream:index/getObject:getObject', __args__, opts=opts, typ=GetObjectResult).value

    return AwaitableGetObjectResult(
        created_at=pulumi.get(__ret__, 'created_at'),
        database=pulumi.get(__ret__, 'database'),
        fqn=pulumi.get(__ret__, 'fqn'),
        id=pulumi.get(__ret__, 'id'),
        name=pulumi.get(__ret__, 'name'),
        namespace=pulumi.get(__ret__, 'namespace'),
        owner=pulumi.get(__ret__, 'owner'),
        state=pulumi.get(__ret__, 'state'),
        type=pulumi.get(__ret__, 'type'),
        updated_at=pulumi.get(__ret__, 'updated_at'))
def get_object_output(database: Optional[pulumi.Input[builtins.str]] = None,
                      name: Optional[pulumi.Input[builtins.str]] = None,
                      namespace: Optional[pulumi.Input[builtins.str]] = None,
                      opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetObjectResult]:
    """
    Object resource


    :param builtins.str database: Name of the Database
    :param builtins.str name: Name of the Object
    :param builtins.str namespace: Name of the Namespace
    """
    __args__ = dict()
    __args__['database'] = database
    __args__['name'] = name
    __args__['namespace'] = namespace
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('deltastream:index/getObject:getObject', __args__, opts=opts, typ=GetObjectResult)
    return __ret__.apply(lambda __response__: GetObjectResult(
        created_at=pulumi.get(__response__, 'created_at'),
        database=pulumi.get(__response__, 'database'),
        fqn=pulumi.get(__response__, 'fqn'),
        id=pulumi.get(__response__, 'id'),
        name=pulumi.get(__response__, 'name'),
        namespace=pulumi.get(__response__, 'namespace'),
        owner=pulumi.get(__response__, 'owner'),
        state=pulumi.get(__response__, 'state'),
        type=pulumi.get(__response__, 'type'),
        updated_at=pulumi.get(__response__, 'updated_at')))
