organization: deltastreaminc
provider: deltastream
major-version: 1
providerDefaultBranch: main
fail-on-missing-mapping: true
fail-on-extra-mapping: true
publishRegistry: true
checkoutSubmodules: false
languages:
  - nodejs
  - go
  # - python
  # - dotnet
  # - java
integrationTestProvider: false
testPulumiExamples: false
runner:
  default: ubuntu-latest
  prerequisites: ubuntu-latest
  # publish: ubuntu-latest
  # buildSdk: ubuntu-latest
publish:
  # passed to the sdk input of pulumi-package-publisher
  # This is overridden in pulumi-local to disable python
  sdk: all
  # Publish the plugin binaries to the Pulumi CDN (get.pulumi.com) - requires AWS credentials for S3 upload
  cdn: false
toolVersions:
  dotnet: "8.0.x"
  go: "1.24.x"
  java: "11"
  gradle: "7.6"
  nodejs: "20.x"
  pulumi: "dev"
  python: "3.11.8"
lint: true
docker: false