// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace DeltaStream.Pulumi
{
    /// <summary>
    /// Object resource
    /// </summary>
    [PulumiResourceType("deltastream:index/object:DeltaStreamObject")]
    public partial class DeltaStreamObject : global::Pulumi.CustomResource
    {
        /// <summary>
        /// Creation date of the object
        /// </summary>
        [Output("createdAt")]
        public Output<string> CreatedAt { get; private set; } = null!;

        /// <summary>
        /// Name of the Database
        /// </summary>
        [Output("database")]
        public Output<string> Database { get; private set; } = null!;

        /// <summary>
        /// Fully qualified name of the Object
        /// </summary>
        [Output("fqn")]
        public Output<string> Fqn { get; private set; } = null!;

        /// <summary>
        /// Name of the Object
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        /// <summary>
        /// Name of the Namespace
        /// </summary>
        [Output("namespace")]
        public Output<string> Namespace { get; private set; } = null!;

        /// <summary>
        /// Owning role of the object
        /// </summary>
        [Output("owner")]
        public Output<string> Owner { get; private set; } = null!;

        /// <summary>
        /// SQL statement to create the object
        /// </summary>
        [Output("sql")]
        public Output<string> Sql { get; private set; } = null!;

        /// <summary>
        /// State of the Object
        /// </summary>
        [Output("state")]
        public Output<string> State { get; private set; } = null!;

        /// <summary>
        /// Name of the Store
        /// </summary>
        [Output("store")]
        public Output<string> Store { get; private set; } = null!;

        /// <summary>
        /// Type of the Object
        /// </summary>
        [Output("type")]
        public Output<string> Type { get; private set; } = null!;

        /// <summary>
        /// Last update date of the object
        /// </summary>
        [Output("updatedAt")]
        public Output<string> UpdatedAt { get; private set; } = null!;


        /// <summary>
        /// Create a DeltaStreamObject resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public DeltaStreamObject(string name, DeltaStreamObjectArgs args, CustomResourceOptions? options = null)
            : base("deltastream:index/object:DeltaStreamObject", name, args ?? new DeltaStreamObjectArgs(), MakeResourceOptions(options, ""))
        {
        }

        private DeltaStreamObject(string name, Input<string> id, DeltaStreamObjectState? state = null, CustomResourceOptions? options = null)
            : base("deltastream:index/object:DeltaStreamObject", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "https://github.com/deltastreaminc/pulumi-deltastream/releases/download/v${VERSION}/",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing DeltaStreamObject resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static DeltaStreamObject Get(string name, Input<string> id, DeltaStreamObjectState? state = null, CustomResourceOptions? options = null)
        {
            return new DeltaStreamObject(name, id, state, options);
        }
    }

    public sealed class DeltaStreamObjectArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Name of the Database
        /// </summary>
        [Input("database", required: true)]
        public Input<string> Database { get; set; } = null!;

        /// <summary>
        /// Name of the Namespace
        /// </summary>
        [Input("namespace", required: true)]
        public Input<string> Namespace { get; set; } = null!;

        /// <summary>
        /// Owning role of the object
        /// </summary>
        [Input("owner")]
        public Input<string>? Owner { get; set; }

        /// <summary>
        /// SQL statement to create the object
        /// </summary>
        [Input("sql", required: true)]
        public Input<string> Sql { get; set; } = null!;

        /// <summary>
        /// Name of the Store
        /// </summary>
        [Input("store", required: true)]
        public Input<string> Store { get; set; } = null!;

        public DeltaStreamObjectArgs()
        {
        }
        public static new DeltaStreamObjectArgs Empty => new DeltaStreamObjectArgs();
    }

    public sealed class DeltaStreamObjectState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Creation date of the object
        /// </summary>
        [Input("createdAt")]
        public Input<string>? CreatedAt { get; set; }

        /// <summary>
        /// Name of the Database
        /// </summary>
        [Input("database")]
        public Input<string>? Database { get; set; }

        /// <summary>
        /// Fully qualified name of the Object
        /// </summary>
        [Input("fqn")]
        public Input<string>? Fqn { get; set; }

        /// <summary>
        /// Name of the Object
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// Name of the Namespace
        /// </summary>
        [Input("namespace")]
        public Input<string>? Namespace { get; set; }

        /// <summary>
        /// Owning role of the object
        /// </summary>
        [Input("owner")]
        public Input<string>? Owner { get; set; }

        /// <summary>
        /// SQL statement to create the object
        /// </summary>
        [Input("sql")]
        public Input<string>? Sql { get; set; }

        /// <summary>
        /// State of the Object
        /// </summary>
        [Input("state")]
        public Input<string>? State { get; set; }

        /// <summary>
        /// Name of the Store
        /// </summary>
        [Input("store")]
        public Input<string>? Store { get; set; }

        /// <summary>
        /// Type of the Object
        /// </summary>
        [Input("type")]
        public Input<string>? Type { get; set; }

        /// <summary>
        /// Last update date of the object
        /// </summary>
        [Input("updatedAt")]
        public Input<string>? UpdatedAt { get; set; }

        public DeltaStreamObjectState()
        {
        }
        public static new DeltaStreamObjectState Empty => new DeltaStreamObjectState();
    }
}
