// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace DeltaStream.Pulumi
{
    public static class GetDatabases
    {
        /// <summary>
        /// Database resource
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Pulumi = Pulumi.Pulumi;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var allDatabases = Pulumi.GetDatabases.Invoke();
        /// 
        /// });
        /// ```
        /// </summary>
        public static Task<GetDatabasesResult> InvokeAsync(InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetDatabasesResult>("deltastream:index/getDatabases:getDatabases", InvokeArgs.Empty, options.WithDefaults());

        /// <summary>
        /// Database resource
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Pulumi = Pulumi.Pulumi;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var allDatabases = Pulumi.GetDatabases.Invoke();
        /// 
        /// });
        /// ```
        /// </summary>
        public static Output<GetDatabasesResult> Invoke(InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetDatabasesResult>("deltastream:index/getDatabases:getDatabases", InvokeArgs.Empty, options.WithDefaults());

        /// <summary>
        /// Database resource
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Pulumi = Pulumi.Pulumi;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var allDatabases = Pulumi.GetDatabases.Invoke();
        /// 
        /// });
        /// ```
        /// </summary>
        public static Output<GetDatabasesResult> Invoke(InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetDatabasesResult>("deltastream:index/getDatabases:getDatabases", InvokeArgs.Empty, options.WithDefaults());
    }


    [OutputType]
    public sealed class GetDatabasesResult
    {
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// List of databases
        /// </summary>
        public readonly ImmutableArray<Outputs.GetDatabasesItemResult> Items;

        [OutputConstructor]
        private GetDatabasesResult(
            string id,

            ImmutableArray<Outputs.GetDatabasesItemResult> items)
        {
            Id = id;
            Items = items;
        }
    }
}
