// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace DeltaStream.Pulumi
{
    public static class GetEntities
    {
        /// <summary>
        /// Entities in a store
        /// </summary>
        public static Task<GetEntitiesResult> InvokeAsync(GetEntitiesArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetEntitiesResult>("deltastream:index/getEntities:getEntities", args ?? new GetEntitiesArgs(), options.WithDefaults());

        /// <summary>
        /// Entities in a store
        /// </summary>
        public static Output<GetEntitiesResult> Invoke(GetEntitiesInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetEntitiesResult>("deltastream:index/getEntities:getEntities", args ?? new GetEntitiesInvokeArgs(), options.WithDefaults());

        /// <summary>
        /// Entities in a store
        /// </summary>
        public static Output<GetEntitiesResult> Invoke(GetEntitiesInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetEntitiesResult>("deltastream:index/getEntities:getEntities", args ?? new GetEntitiesInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetEntitiesArgs : global::Pulumi.InvokeArgs
    {
        [Input("parentPaths")]
        private List<string>? _parentPaths;

        /// <summary>
        /// Path to parent entity
        /// </summary>
        public List<string> ParentPaths
        {
            get => _parentPaths ?? (_parentPaths = new List<string>());
            set => _parentPaths = value;
        }

        /// <summary>
        /// Name of the Store
        /// </summary>
        [Input("store", required: true)]
        public string Store { get; set; } = null!;

        public GetEntitiesArgs()
        {
        }
        public static new GetEntitiesArgs Empty => new GetEntitiesArgs();
    }

    public sealed class GetEntitiesInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("parentPaths")]
        private InputList<string>? _parentPaths;

        /// <summary>
        /// Path to parent entity
        /// </summary>
        public InputList<string> ParentPaths
        {
            get => _parentPaths ?? (_parentPaths = new InputList<string>());
            set => _parentPaths = value;
        }

        /// <summary>
        /// Name of the Store
        /// </summary>
        [Input("store", required: true)]
        public Input<string> Store { get; set; } = null!;

        public GetEntitiesInvokeArgs()
        {
        }
        public static new GetEntitiesInvokeArgs Empty => new GetEntitiesInvokeArgs();
    }


    [OutputType]
    public sealed class GetEntitiesResult
    {
        /// <summary>
        /// Child entities
        /// </summary>
        public readonly ImmutableArray<string> ChildEntities;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// Path to parent entity
        /// </summary>
        public readonly ImmutableArray<string> ParentPaths;
        /// <summary>
        /// Name of the Store
        /// </summary>
        public readonly string Store;

        [OutputConstructor]
        private GetEntitiesResult(
            ImmutableArray<string> childEntities,

            string id,

            ImmutableArray<string> parentPaths,

            string store)
        {
            ChildEntities = childEntities;
            Id = id;
            ParentPaths = parentPaths;
            Store = store;
        }
    }
}
