// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace DeltaStream.Pulumi
{
    public static class GetObject
    {
        /// <summary>
        /// Object resource
        /// </summary>
        public static Task<GetObjectResult> InvokeAsync(GetObjectArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetObjectResult>("deltastream:index/getObject:getObject", args ?? new GetObjectArgs(), options.WithDefaults());

        /// <summary>
        /// Object resource
        /// </summary>
        public static Output<GetObjectResult> Invoke(GetObjectInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetObjectResult>("deltastream:index/getObject:getObject", args ?? new GetObjectInvokeArgs(), options.WithDefaults());

        /// <summary>
        /// Object resource
        /// </summary>
        public static Output<GetObjectResult> Invoke(GetObjectInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetObjectResult>("deltastream:index/getObject:getObject", args ?? new GetObjectInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetObjectArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// Name of the Database
        /// </summary>
        [Input("database", required: true)]
        public string Database { get; set; } = null!;

        /// <summary>
        /// Name of the Object
        /// </summary>
        [Input("name", required: true)]
        public string Name { get; set; } = null!;

        /// <summary>
        /// Name of the Namespace
        /// </summary>
        [Input("namespace", required: true)]
        public string Namespace { get; set; } = null!;

        public GetObjectArgs()
        {
        }
        public static new GetObjectArgs Empty => new GetObjectArgs();
    }

    public sealed class GetObjectInvokeArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// Name of the Database
        /// </summary>
        [Input("database", required: true)]
        public Input<string> Database { get; set; } = null!;

        /// <summary>
        /// Name of the Object
        /// </summary>
        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        /// <summary>
        /// Name of the Namespace
        /// </summary>
        [Input("namespace", required: true)]
        public Input<string> Namespace { get; set; } = null!;

        public GetObjectInvokeArgs()
        {
        }
        public static new GetObjectInvokeArgs Empty => new GetObjectInvokeArgs();
    }


    [OutputType]
    public sealed class GetObjectResult
    {
        /// <summary>
        /// Creation date of the object
        /// </summary>
        public readonly string CreatedAt;
        /// <summary>
        /// Name of the Database
        /// </summary>
        public readonly string Database;
        /// <summary>
        /// Fully qualified name of the Object
        /// </summary>
        public readonly string Fqn;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// Name of the Object
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// Name of the Namespace
        /// </summary>
        public readonly string Namespace;
        /// <summary>
        /// Owning role of the object
        /// </summary>
        public readonly string Owner;
        /// <summary>
        /// State of the Object
        /// </summary>
        public readonly string State;
        /// <summary>
        /// Type of the Object
        /// </summary>
        public readonly string Type;
        /// <summary>
        /// Last update date of the object
        /// </summary>
        public readonly string UpdatedAt;

        [OutputConstructor]
        private GetObjectResult(
            string createdAt,

            string database,

            string fqn,

            string id,

            string name,

            string @namespace,

            string owner,

            string state,

            string type,

            string updatedAt)
        {
            CreatedAt = createdAt;
            Database = database;
            Fqn = fqn;
            Id = id;
            Name = name;
            Namespace = @namespace;
            Owner = owner;
            State = state;
            Type = type;
            UpdatedAt = updatedAt;
        }
    }
}
