// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace DeltaStream.Pulumi
{
    public static class GetSecrets
    {
        /// <summary>
        /// Secret resource
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Pulumi = Pulumi.Pulumi;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var allSecrets = Pulumi.GetSecrets.Invoke();
        /// 
        /// });
        /// ```
        /// </summary>
        public static Task<GetSecretsResult> InvokeAsync(InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetSecretsResult>("deltastream:index/getSecrets:getSecrets", InvokeArgs.Empty, options.WithDefaults());

        /// <summary>
        /// Secret resource
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Pulumi = Pulumi.Pulumi;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var allSecrets = Pulumi.GetSecrets.Invoke();
        /// 
        /// });
        /// ```
        /// </summary>
        public static Output<GetSecretsResult> Invoke(InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetSecretsResult>("deltastream:index/getSecrets:getSecrets", InvokeArgs.Empty, options.WithDefaults());

        /// <summary>
        /// Secret resource
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Pulumi = Pulumi.Pulumi;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var allSecrets = Pulumi.GetSecrets.Invoke();
        /// 
        /// });
        /// ```
        /// </summary>
        public static Output<GetSecretsResult> Invoke(InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetSecretsResult>("deltastream:index/getSecrets:getSecrets", InvokeArgs.Empty, options.WithDefaults());
    }


    [OutputType]
    public sealed class GetSecretsResult
    {
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// List of secrets
        /// </summary>
        public readonly ImmutableArray<Outputs.GetSecretsItemResult> Items;

        [OutputConstructor]
        private GetSecretsResult(
            string id,

            ImmutableArray<Outputs.GetSecretsItemResult> items)
        {
            Id = id;
            Items = items;
        }
    }
}
