// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace DeltaStream.Pulumi
{
    public static class GetSchemaRegistries
    {
        /// <summary>
        /// Schema registries datasource
        /// </summary>
        public static Task<GetSchemaRegistriesResult> InvokeAsync(InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetSchemaRegistriesResult>("deltastream:index/getSchemaRegistries:getSchemaRegistries", InvokeArgs.Empty, options.WithDefaults());

        /// <summary>
        /// Schema registries datasource
        /// </summary>
        public static Output<GetSchemaRegistriesResult> Invoke(InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetSchemaRegistriesResult>("deltastream:index/getSchemaRegistries:getSchemaRegistries", InvokeArgs.Empty, options.WithDefaults());

        /// <summary>
        /// Schema registries datasource
        /// </summary>
        public static Output<GetSchemaRegistriesResult> Invoke(InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetSchemaRegistriesResult>("deltastream:index/getSchemaRegistries:getSchemaRegistries", InvokeArgs.Empty, options.WithDefaults());
    }


    [OutputType]
    public sealed class GetSchemaRegistriesResult
    {
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// List of schema registries
        /// </summary>
        public readonly ImmutableArray<Outputs.GetSchemaRegistriesItemResult> Items;

        [OutputConstructor]
        private GetSchemaRegistriesResult(
            string id,

            ImmutableArray<Outputs.GetSchemaRegistriesItemResult> items)
        {
            Id = id;
            Items = items;
        }
    }
}
