// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace DeltaStream.Pulumi
{
    public static class GetSchemaRegistry
    {
        /// <summary>
        /// Schema registry datasource
        /// </summary>
        public static Task<GetSchemaRegistryResult> InvokeAsync(GetSchemaRegistryArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetSchemaRegistryResult>("deltastream:index/getSchemaRegistry:getSchemaRegistry", args ?? new GetSchemaRegistryArgs(), options.WithDefaults());

        /// <summary>
        /// Schema registry datasource
        /// </summary>
        public static Output<GetSchemaRegistryResult> Invoke(GetSchemaRegistryInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetSchemaRegistryResult>("deltastream:index/getSchemaRegistry:getSchemaRegistry", args ?? new GetSchemaRegistryInvokeArgs(), options.WithDefaults());

        /// <summary>
        /// Schema registry datasource
        /// </summary>
        public static Output<GetSchemaRegistryResult> Invoke(GetSchemaRegistryInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetSchemaRegistryResult>("deltastream:index/getSchemaRegistry:getSchemaRegistry", args ?? new GetSchemaRegistryInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetSchemaRegistryArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// Name of the schema registry
        /// </summary>
        [Input("name", required: true)]
        public string Name { get; set; } = null!;

        public GetSchemaRegistryArgs()
        {
        }
        public static new GetSchemaRegistryArgs Empty => new GetSchemaRegistryArgs();
    }

    public sealed class GetSchemaRegistryInvokeArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// Name of the schema registry
        /// </summary>
        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        public GetSchemaRegistryInvokeArgs()
        {
        }
        public static new GetSchemaRegistryInvokeArgs Empty => new GetSchemaRegistryInvokeArgs();
    }


    [OutputType]
    public sealed class GetSchemaRegistryResult
    {
        /// <summary>
        /// Creation date of the schema registry
        /// </summary>
        public readonly string CreatedAt;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// Name of the schema registry
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// Owning role of the schema registry
        /// </summary>
        public readonly string Owner;
        /// <summary>
        /// State of the schema registry
        /// </summary>
        public readonly string State;
        /// <summary>
        /// Type of the schema registry
        /// </summary>
        public readonly string Type;
        /// <summary>
        /// Last update date of the schema registry
        /// </summary>
        public readonly string UpdatedAt;

        [OutputConstructor]
        private GetSchemaRegistryResult(
            string createdAt,

            string id,

            string name,

            string owner,

            string state,

            string type,

            string updatedAt)
        {
            CreatedAt = createdAt;
            Id = id;
            Name = name;
            Owner = owner;
            State = state;
            Type = type;
            UpdatedAt = updatedAt;
        }
    }
}
