// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package config

import (
	"github.com/deltastreaminc/pulumi-deltastream/sdk/go/pulumi-deltastream/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi/config"
)

var _ = internal.GetEnvOrDefault

func GetApiKey(ctx *pulumi.Context) string {
	return config.Get(ctx, "deltastream:apiKey")
}
func GetInsecureSkipVerify(ctx *pulumi.Context) bool {
	return config.GetBool(ctx, "deltastream:insecureSkipVerify")
}
func GetOrganization(ctx *pulumi.Context) string {
	return config.Get(ctx, "deltastream:organization")
}
func GetRole(ctx *pulumi.Context) string {
	return config.Get(ctx, "deltastream:role")
}
func GetServer(ctx *pulumi.Context) string {
	return config.Get(ctx, "deltastream:server")
}
func GetSessionId(ctx *pulumi.Context) string {
	return config.Get(ctx, "deltastream:sessionId")
}
