// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

declare var exports: any;
const __config = new pulumi.Config("deltastream");

/**
 * API key. Can also be set via the DELTASTREAM_API_KEY environment variable
 */
export declare const apiKey: string | undefined;
Object.defineProperty(exports, "apiKey", {
    get() {
        return __config.get("apiKey");
    },
    enumerable: true,
});

/**
 * Skip SSL verification
 */
export declare const insecureSkipVerify: boolean | undefined;
Object.defineProperty(exports, "insecureSkipVerify", {
    get() {
        return __config.getObject<boolean>("insecureSkipVerify");
    },
    enumerable: true,
});

/**
 * DeltaStream organization ID. Can also be set via the DELTASTREAM_ORGANIZATION environment variable.
 */
export declare const organization: string | undefined;
Object.defineProperty(exports, "organization", {
    get() {
        return __config.get("organization");
    },
    enumerable: true,
});

/**
 * DeltaStream role to use for managing resources and queries. Can also be set via the DELTASTREAM_ROLE environment
 * variable. Default: sysadmin
 */
export declare const role: string | undefined;
Object.defineProperty(exports, "role", {
    get() {
        return __config.get("role");
    },
    enumerable: true,
});

/**
 * Server. Can also be set via the DELTASTREAM_SERVER environment variable
 */
export declare const server: string | undefined;
Object.defineProperty(exports, "server", {
    get() {
        return __config.get("server");
    },
    enumerable: true,
});

