// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace DeltaStream.Pulumi.Outputs
{

    [OutputType]
    public sealed class GetDatabasesItemResult
    {
        /// <summary>
        /// Creation date of the Database
        /// </summary>
        public readonly string CreatedAt;
        /// <summary>
        /// Name of the Database
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// Owning role of the Database
        /// </summary>
        public readonly string Owner;

        [OutputConstructor]
        private GetDatabasesItemResult(
            string createdAt,

            string name,

            string owner)
        {
            CreatedAt = createdAt;
            Name = name;
            Owner = owner;
        }
    }
}
