// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace DeltaStream.Pulumi.Outputs
{

    [OutputType]
    public sealed class GetObjectsObjectResult
    {
        /// <summary>
        /// Creation date of the object
        /// </summary>
        public readonly string CreatedAt;
        /// <summary>
        /// Name of the Database
        /// </summary>
        public readonly string Database;
        /// <summary>
        /// Fully qualified name of the Object
        /// </summary>
        public readonly string Fqn;
        /// <summary>
        /// Name of the Object
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// Name of the Namespace
        /// </summary>
        public readonly string Namespace;
        /// <summary>
        /// Owning role of the object
        /// </summary>
        public readonly string Owner;
        /// <summary>
        /// State of the Object
        /// </summary>
        public readonly string State;
        /// <summary>
        /// Type of the Object
        /// </summary>
        public readonly string Type;
        /// <summary>
        /// Last update date of the object
        /// </summary>
        public readonly string UpdatedAt;

        [OutputConstructor]
        private GetObjectsObjectResult(
            string createdAt,

            string database,

            string fqn,

            string name,

            string @namespace,

            string owner,

            string state,

            string type,

            string updatedAt)
        {
            CreatedAt = createdAt;
            Database = database;
            Fqn = fqn;
            Name = name;
            Namespace = @namespace;
            Owner = owner;
            State = state;
            Type = type;
            UpdatedAt = updatedAt;
        }
    }
}
