// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace DeltaStream.Pulumi.Outputs
{

    [OutputType]
    public sealed class GetSecretsItemResult
    {
        /// <summary>
        /// Creation date of the Secret
        /// </summary>
        public readonly string CreatedAt;
        /// <summary>
        /// Description of the Secret
        /// </summary>
        public readonly string Description;
        /// <summary>
        /// Name of the Secret
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// Owning role of the Secret
        /// </summary>
        public readonly string Owner;
        /// <summary>
        /// Status of the Secret
        /// </summary>
        public readonly string Status;
        /// <summary>
        /// Secret type. (Valid values: generic_string)
        /// </summary>
        public readonly string Type;
        /// <summary>
        /// Last update date of the Secret
        /// </summary>
        public readonly string UpdatedAt;

        [OutputConstructor]
        private GetSecretsItemResult(
            string createdAt,

            string description,

            string name,

            string owner,

            string status,

            string type,

            string updatedAt)
        {
            CreatedAt = createdAt;
            Description = description;
            Name = name;
            Owner = owner;
            Status = status;
            Type = type;
            UpdatedAt = updatedAt;
        }
    }
}
