// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace DeltaStream.Pulumi.Outputs
{

    [OutputType]
    public sealed class GetSchemaRegistriesItemResult
    {
        /// <summary>
        /// Creation date of the schema registry
        /// </summary>
        public readonly string CreatedAt;
        /// <summary>
        /// Name of the schema registry
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// Owning role of the schema registry
        /// </summary>
        public readonly string Owner;
        /// <summary>
        /// State of the schema registry
        /// </summary>
        public readonly string State;
        /// <summary>
        /// Type of the schema registry
        /// </summary>
        public readonly string Type;
        /// <summary>
        /// Last update date of the schema registry
        /// </summary>
        public readonly string UpdatedAt;

        [OutputConstructor]
        private GetSchemaRegistriesItemResult(
            string createdAt,

            string name,

            string owner,

            string state,

            string type,

            string updatedAt)
        {
            CreatedAt = createdAt;
            Name = name;
            Owner = owner;
            State = state;
            Type = type;
            UpdatedAt = updatedAt;
        }
    }
}
