// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace DeltaStream.Pulumi.Outputs
{

    [OutputType]
    public sealed class StoreKinesis
    {
        /// <summary>
        /// AWS IAM access key to use when authenticating with an Amazon Kinesis service
        /// </summary>
        public readonly string? AccessKeyId;
        /// <summary>
        /// AWS account ID to use when authenticating with an Amazon Kinesis service
        /// </summary>
        public readonly string AwsAccountId;
        /// <summary>
        /// AWS IAM secret access key to use when authenticating with an Amazon Kinesis service
        /// </summary>
        public readonly string? SecretAccessKey;
        /// <summary>
        /// List of host:port URIs to connect to the store
        /// </summary>
        public readonly string Uris;

        [OutputConstructor]
        private StoreKinesis(
            string? accessKeyId,

            string awsAccountId,

            string? secretAccessKey,

            string uris)
        {
            AccessKeyId = accessKeyId;
            AwsAccountId = awsAccountId;
            SecretAccessKey = secretAccessKey;
            Uris = uris;
        }
    }
}
