// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace DeltaStream.Pulumi.Outputs
{

    [OutputType]
    public sealed class StoreConfluentKafka
    {
        /// <summary>
        /// SASL hash function to use when authenticating with Confluent Kafka brokers
        /// </summary>
        public readonly string SaslHashFunction;
        /// <summary>
        /// Password to use when authenticating with Apache Kafka brokers
        /// </summary>
        public readonly string SaslPassword;
        /// <summary>
        /// Username to use when authenticating with Apache Kafka brokers
        /// </summary>
        public readonly string SaslUsername;
        /// <summary>
        /// List of host:port URIs to connect to the store
        /// </summary>
        public readonly string Uris;

        [OutputConstructor]
        private StoreConfluentKafka(
            string saslHashFunction,

            string saslPassword,

            string saslUsername,

            string uris)
        {
            SaslHashFunction = saslHashFunction;
            SaslPassword = saslPassword;
            SaslUsername = saslUsername;
            Uris = uris;
        }
    }
}
