// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace DeltaStream.Pulumi.Outputs
{

    [OutputType]
    public sealed class StorePostgres
    {
        /// <summary>
        /// Password to use when authenticating with a Postgres database
        /// </summary>
        public readonly string Password;
        /// <summary>
        /// List of host:port URIs to connect to the store
        /// </summary>
        public readonly string Uris;
        /// <summary>
        /// Username to use when authenticating with a Postgres database
        /// </summary>
        public readonly string Username;

        [OutputConstructor]
        private StorePostgres(
            string password,

            string uris,

            string username)
        {
            Password = password;
            Uris = uris;
            Username = username;
        }
    }
}
