// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package deltastream

import (
	"fmt"

	"github.com/blang/semver"
	"github.com/deltastreaminc/pulumi-deltastream/sdk/go/deltastream/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type module struct {
	version semver.Version
}

func (m *module) Version() semver.Version {
	return m.version
}

func (m *module) Construct(ctx *pulumi.Context, name, typ, urn string) (r pulumi.Resource, err error) {
	switch typ {
	case "deltastream:index/database:Database":
		r = &Database{}
	case "deltastream:index/entity:Entity":
		r = &Entity{}
	case "deltastream:index/namespace:Namespace":
		r = &Namespace{}
	case "deltastream:index/object:DeltaStreamObject":
		r = &DeltaStreamObject{}
	case "deltastream:index/query:Query":
		r = &Query{}
	case "deltastream:index/schemaRegistry:SchemaRegistry":
		r = &SchemaRegistry{}
	case "deltastream:index/secret:Secret":
		r = &Secret{}
	case "deltastream:index/store:Store":
		r = &Store{}
	default:
		return nil, fmt.Errorf("unknown resource type: %s", typ)
	}

	err = ctx.RegisterResource(typ, name, nil, r, pulumi.URN_(urn))
	return
}

type pkg struct {
	version semver.Version
}

func (p *pkg) Version() semver.Version {
	return p.version
}

func (p *pkg) ConstructProvider(ctx *pulumi.Context, name, typ, urn string) (pulumi.ProviderResource, error) {
	if typ != "pulumi:providers:deltastream" {
		return nil, fmt.Errorf("unknown provider type: %s", typ)
	}

	r := &Provider{}
	err := ctx.RegisterResource(typ, name, nil, r, pulumi.URN_(urn))
	return r, err
}

func init() {
	version, err := internal.PkgVersion()
	if err != nil {
		version = semver.Version{Major: 1}
	}
	pulumi.RegisterResourceModule(
		"deltastream",
		"index/database",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"deltastream",
		"index/entity",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"deltastream",
		"index/namespace",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"deltastream",
		"index/object",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"deltastream",
		"index/query",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"deltastream",
		"index/schemaRegistry",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"deltastream",
		"index/secret",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"deltastream",
		"index/store",
		&module{version},
	)
	pulumi.RegisterResourcePackage(
		"deltastream",
		&pkg{version},
	)
}
