// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package deltastream

import (
	"context"
	"reflect"

	"github.com/deltastreaminc/pulumi-deltastream/sdk/go/deltastream/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// The provider type for the deltastream package. By default, resources use package-wide configuration
// settings, however an explicit `Provider` instance may be created and passed during resource
// construction to achieve fine-grained programmatic control over provider settings. See the
// [documentation](https://www.pulumi.com/docs/reference/programming-model/#providers) for more information.
type Provider struct {
	pulumi.ProviderResourceState

	// API key. Can also be set via the DELTASTREAM_API_KEY environment variable
	ApiKey pulumi.StringPtrOutput `pulumi:"apiKey"`
	// DeltaStream organization ID. Can also be set via the DELTASTREAM_ORGANIZATION environment variable.
	Organization pulumi.StringPtrOutput `pulumi:"organization"`
	// DeltaStream role to use for managing resources and queries. Can also be set via the DELTASTREAM_ROLE environment
	// variable. Default: sysadmin
	Role pulumi.StringPtrOutput `pulumi:"role"`
	// Server. Can also be set via the DELTASTREAM_SERVER environment variable
	Server pulumi.StringPtrOutput `pulumi:"server"`
}

// NewProvider registers a new resource with the given unique name, arguments, and options.
func NewProvider(ctx *pulumi.Context,
	name string, args *ProviderArgs, opts ...pulumi.ResourceOption) (*Provider, error) {
	if args == nil {
		args = &ProviderArgs{}
	}

	opts = internal.PkgResourceDefaultOpts(opts)
	var resource Provider
	err := ctx.RegisterResource("pulumi:providers:deltastream", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

type providerArgs struct {
	// API key. Can also be set via the DELTASTREAM_API_KEY environment variable
	ApiKey *string `pulumi:"apiKey"`
	// Skip SSL verification
	InsecureSkipVerify *bool `pulumi:"insecureSkipVerify"`
	// DeltaStream organization ID. Can also be set via the DELTASTREAM_ORGANIZATION environment variable.
	Organization *string `pulumi:"organization"`
	// DeltaStream role to use for managing resources and queries. Can also be set via the DELTASTREAM_ROLE environment
	// variable. Default: sysadmin
	Role *string `pulumi:"role"`
	// Server. Can also be set via the DELTASTREAM_SERVER environment variable
	Server *string `pulumi:"server"`
}

// The set of arguments for constructing a Provider resource.
type ProviderArgs struct {
	// API key. Can also be set via the DELTASTREAM_API_KEY environment variable
	ApiKey pulumi.StringPtrInput
	// Skip SSL verification
	InsecureSkipVerify pulumi.BoolPtrInput
	// DeltaStream organization ID. Can also be set via the DELTASTREAM_ORGANIZATION environment variable.
	Organization pulumi.StringPtrInput
	// DeltaStream role to use for managing resources and queries. Can also be set via the DELTASTREAM_ROLE environment
	// variable. Default: sysadmin
	Role pulumi.StringPtrInput
	// Server. Can also be set via the DELTASTREAM_SERVER environment variable
	Server pulumi.StringPtrInput
}

func (ProviderArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*providerArgs)(nil)).Elem()
}

// This function returns a Terraform config object with terraform-namecased keys,to be used with the Terraform Module Provider.
func (r *Provider) TerraformConfig(ctx *pulumi.Context) (ProviderTerraformConfigResultOutput, error) {
	out, err := ctx.Call("pulumi:providers:deltastream/terraformConfig", nil, ProviderTerraformConfigResultOutput{}, r)
	if err != nil {
		return ProviderTerraformConfigResultOutput{}, err
	}
	return out.(ProviderTerraformConfigResultOutput), nil
}

type ProviderTerraformConfigResult struct {
	Result map[string]interface{} `pulumi:"result"`
}

type ProviderTerraformConfigResultOutput struct{ *pulumi.OutputState }

func (ProviderTerraformConfigResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*ProviderTerraformConfigResult)(nil)).Elem()
}

func (o ProviderTerraformConfigResultOutput) Result() pulumi.MapOutput {
	return o.ApplyT(func(v ProviderTerraformConfigResult) map[string]interface{} { return v.Result }).(pulumi.MapOutput)
}

type ProviderInput interface {
	pulumi.Input

	ToProviderOutput() ProviderOutput
	ToProviderOutputWithContext(ctx context.Context) ProviderOutput
}

func (*Provider) ElementType() reflect.Type {
	return reflect.TypeOf((**Provider)(nil)).Elem()
}

func (i *Provider) ToProviderOutput() ProviderOutput {
	return i.ToProviderOutputWithContext(context.Background())
}

func (i *Provider) ToProviderOutputWithContext(ctx context.Context) ProviderOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ProviderOutput)
}

type ProviderOutput struct{ *pulumi.OutputState }

func (ProviderOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Provider)(nil)).Elem()
}

func (o ProviderOutput) ToProviderOutput() ProviderOutput {
	return o
}

func (o ProviderOutput) ToProviderOutputWithContext(ctx context.Context) ProviderOutput {
	return o
}

// API key. Can also be set via the DELTASTREAM_API_KEY environment variable
func (o ProviderOutput) ApiKey() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Provider) pulumi.StringPtrOutput { return v.ApiKey }).(pulumi.StringPtrOutput)
}

// DeltaStream organization ID. Can also be set via the DELTASTREAM_ORGANIZATION environment variable.
func (o ProviderOutput) Organization() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Provider) pulumi.StringPtrOutput { return v.Organization }).(pulumi.StringPtrOutput)
}

// DeltaStream role to use for managing resources and queries. Can also be set via the DELTASTREAM_ROLE environment
// variable. Default: sysadmin
func (o ProviderOutput) Role() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Provider) pulumi.StringPtrOutput { return v.Role }).(pulumi.StringPtrOutput)
}

// Server. Can also be set via the DELTASTREAM_SERVER environment variable
func (o ProviderOutput) Server() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Provider) pulumi.StringPtrOutput { return v.Server }).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*ProviderInput)(nil)).Elem(), &Provider{})
	pulumi.RegisterOutputType(ProviderOutput{})
	pulumi.RegisterOutputType(ProviderTerraformConfigResultOutput{})
}
