// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace DeltaStream.Pulumi.Inputs
{

    public sealed class EntityPostgresPropertiesArgs : global::Pulumi.ResourceArgs
    {
        [Input("details")]
        private InputMap<string>? _details;
        public InputMap<string> Details
        {
            get => _details ?? (_details = new InputMap<string>());
            set => _details = value;
        }

        public EntityPostgresPropertiesArgs()
        {
        }
        public static new EntityPostgresPropertiesArgs Empty => new EntityPostgresPropertiesArgs();
    }
}
