// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace DeltaStream.Pulumi.Inputs
{

    public sealed class EntityKafkaPropertiesArgs : global::Pulumi.ResourceArgs
    {
        [Input("allConfigs")]
        private InputMap<string>? _allConfigs;

        /// <summary>
        /// All topic configurations including any server set configurations
        /// </summary>
        public InputMap<string> AllConfigs
        {
            get => _allConfigs ?? (_allConfigs = new InputMap<string>());
            set => _allConfigs = value;
        }

        [Input("configs")]
        private InputMap<string>? _configs;

        /// <summary>
        /// Additional topic configurations
        /// </summary>
        public InputMap<string> Configs
        {
            get => _configs ?? (_configs = new InputMap<string>());
            set => _configs = value;
        }

        /// <summary>
        /// Protobuf descriptor for key
        /// </summary>
        [Input("keyDescriptor")]
        public Input<string>? KeyDescriptor { get; set; }

        /// <summary>
        /// Number of partitions
        /// </summary>
        [Input("topicPartitions")]
        public Input<int>? TopicPartitions { get; set; }

        /// <summary>
        /// Number of replicas
        /// </summary>
        [Input("topicReplicas")]
        public Input<int>? TopicReplicas { get; set; }

        /// <summary>
        /// Protobuf descriptor for value
        /// </summary>
        [Input("valueDescriptor")]
        public Input<string>? ValueDescriptor { get; set; }

        public EntityKafkaPropertiesArgs()
        {
        }
        public static new EntityKafkaPropertiesArgs Empty => new EntityKafkaPropertiesArgs();
    }
}
