// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace DeltaStream.Pulumi.Inputs
{

    public sealed class GetStoreKinesisInputArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Name of the schema registry
        /// </summary>
        [Input("schemaRegistryName", required: true)]
        public Input<string> SchemaRegistryName { get; set; } = null!;

        /// <summary>
        /// List of host:port URIs to connect to the store
        /// </summary>
        [Input("uris", required: true)]
        public Input<string> Uris { get; set; } = null!;

        public GetStoreKinesisInputArgs()
        {
        }
        public static new GetStoreKinesisInputArgs Empty => new GetStoreKinesisInputArgs();
    }
}
