// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace DeltaStream.Pulumi.Inputs
{

    public sealed class GetStorePostgresInputArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// List of host:port URIs to connect to the store
        /// </summary>
        [Input("uris", required: true)]
        public Input<string> Uris { get; set; } = null!;

        public GetStorePostgresInputArgs()
        {
        }
        public static new GetStorePostgresInputArgs Empty => new GetStorePostgresInputArgs();
    }
}
