// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace DeltaStream.Pulumi.Inputs
{

    public sealed class GetStoreSnowflakeArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// Snowflake account ID
        /// </summary>
        [Input("accountId", required: true)]
        public string AccountId { get; set; } = null!;

        /// <summary>
        /// Access control role to use for the Store operations after connecting to Snowflake
        /// </summary>
        [Input("roleName", required: true)]
        public string RoleName { get; set; } = null!;

        /// <summary>
        /// List of host:port URIs to connect to the store
        /// </summary>
        [Input("uris", required: true)]
        public string Uris { get; set; } = null!;

        /// <summary>
        /// Warehouse name to use for queries and other store operations that require compute resource
        /// </summary>
        [Input("warehouseName", required: true)]
        public string WarehouseName { get; set; } = null!;

        public GetStoreSnowflakeArgs()
        {
        }
        public static new GetStoreSnowflakeArgs Empty => new GetStoreSnowflakeArgs();
    }
}
