name: CI

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'PR number to test'
        required: true

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      is_fork: ${{ steps.check.outputs.is_fork }}
    steps:
      - name: Check if PR is from fork
        id: check
        run: echo "is_fork=${{ github.event.pull_request.head.repo.full_name != github.repository }}" >> $GITHUB_OUTPUT

  build:
    needs: setup
    # Build job can run for all PRs since it doesn't use secrets
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.x'
      - name: Setup Pulumi
        uses: pulumi/actions@v4
        with:
          pulumi-version: '>=3.182.0'
      - name: Build
        run: make clean build schema generate build_sdks
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'yarn'
          cache-dependency-path: sdk/nodejs/yarn.lock
      - name: Install Yarn
        run: npm install -g yarn@1.22.22
      - name: Upload provider build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: provider-build
          path: |
            bin/**
            schema.json
            sdk/**
      - name: Upload yarn.lock artifact
        uses: actions/upload-artifact@v4
        with:
          name: yarn-lock
          path: sdk/nodejs/yarn.lock

  test:
    needs: [setup, build]
    # Only run automatically if PR is not from a fork, otherwise needs manual approval
    if: ${{ needs.setup.outputs.is_fork == 'false' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.x'
      - name: Setup Pulumi
        uses: pulumi/actions@v4
        with:
          pulumi-version: '>=3.182.0'
      # Download artifacts BEFORE setting up Node to ensure yarn.lock is present for caching
      - name: Download provider build artifacts
        uses: actions/download-artifact@v4
        with:
          name: provider-build
          path: .
      - name: Download yarn.lock artifact
        uses: actions/download-artifact@v4
        with:
          name: yarn-lock
          path: sdk/nodejs
      - name: Restore executable permissions
        run: |
          if [ -d bin ]; then chmod +x bin/* || true; fi
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'yarn'
          cache-dependency-path: sdk/nodejs/yarn.lock
      - name: Install Yarn
        run: npm install -g yarn@1.22.22
      - name: Setup credentials
        run: |
          mkdir -p ~/.pulumi-deltastream
          echo "${{ secrets.CI_CREDENTIALS_YAML }}" > examples/credentials.yaml
      - name: Run tests
        run: make install_sdks test
