name: Slash Run Tests

on:
  issue_comment:
    types: [created]

permissions:
  contents: write
  pull-requests: read

jobs:
  dispatch-run-tests:
    if: >-
      ${{ github.event.issue.pull_request && contains(github.event.comment.body, '/test') &&
          ( github.event.comment.author_association == 'MEMBER' ||
            github.event.comment.author_association == 'OWNER' ) }}
    runs-on: ubuntu-latest
    steps:
      - name: Emit repository_dispatch with payload
        uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
        with:
          script: |
            // Send an auxiliary repository_dispatch including PR number & current head SHA
            const prNumber = context.issue.number;
            const { data: pr } = await github.rest.pulls.get({owner: context.repo.owner, repo: context.repo.repo, pull_number: prNumber});
            await github.rest.repos.createDispatchEvent({
              owner: context.repo.owner,
              repo: context.repo.repo,
              event_type: 'test',
              client_payload: { pr: prNumber, sha: pr.head.sha }
            });
