name: Slash Run Tests

on:
  issue_comment:
    types: [created]

permissions:
  contents: read
  pull-requests: read

jobs:
  dispatch-run-tests:
    if: >-
      ${{ github.event.issue.pull_request && startsWith(github.event.comment.body, '/run tests') }}
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch run-tests event
        uses: peter-evans/slash-command-dispatch@13bc09769d122a64f75aa5037256f6f2d78be8c4 # v4.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          permission: write
          commands: run-tests
          issue-type: pull-request
