name: Slash Run Tests

on:
  issue_comment:
    types: [created]

permissions:
  contents: write
  pull-requests: read

jobs:
  dispatch-run-tests:
    if: >-
      ${{ github.event.issue.pull_request && contains(github.event.comment.body, '/test') &&
          ( github.event.comment.author_association == 'MEMBER' ||
            github.event.comment.author_association == 'OWNER' ) }}
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch test event
        uses: peter-evans/slash-command-dispatch@13bc09769d122a64f75aa5037256f6f2d78be8c4 # v4.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          permission: write
          commands: test
          issue-type: pull-request
          event-type-suffix: ''
