// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * Database resource
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as deltastream from "@deltastream/pulumi";
 *
 * const allDatabases = deltastream.getDatabases({});
 * ```
 */
export function getDatabases(opts?: pulumi.InvokeOptions): Promise<GetDatabasesResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("deltastream:index/getDatabases:getDatabases", {
    }, opts);
}

/**
 * A collection of values returned by getDatabases.
 */
export interface GetDatabasesResult {
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    /**
     * List of databases
     */
    readonly items: outputs.GetDatabasesItem[];
}
/**
 * Database resource
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as deltastream from "@deltastream/pulumi";
 *
 * const allDatabases = deltastream.getDatabases({});
 * ```
 */
export function getDatabasesOutput(opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetDatabasesResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("deltastream:index/getDatabases:getDatabases", {
    }, opts);
}
