// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Object resource
 */
export function getObject(args: GetObjectArgs, opts?: pulumi.InvokeOptions): Promise<GetObjectResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("deltastream:index/getObject:getObject", {
        "database": args.database,
        "name": args.name,
        "namespace": args.namespace,
    }, opts);
}

/**
 * A collection of arguments for invoking getObject.
 */
export interface GetObjectArgs {
    /**
     * Name of the Database
     */
    database: string;
    /**
     * Name of the Object
     */
    name: string;
    /**
     * Name of the Namespace
     */
    namespace: string;
}

/**
 * A collection of values returned by getObject.
 */
export interface GetObjectResult {
    /**
     * Creation date of the object
     */
    readonly createdAt: string;
    /**
     * Name of the Database
     */
    readonly database: string;
    /**
     * Fully qualified name of the Object
     */
    readonly fqn: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    /**
     * Name of the Object
     */
    readonly name: string;
    /**
     * Name of the Namespace
     */
    readonly namespace: string;
    /**
     * Owning role of the object
     */
    readonly owner: string;
    /**
     * State of the Object
     */
    readonly state: string;
    /**
     * Type of the Object
     */
    readonly type: string;
    /**
     * Last update date of the object
     */
    readonly updatedAt: string;
}
/**
 * Object resource
 */
export function getObjectOutput(args: GetObjectOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetObjectResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("deltastream:index/getObject:getObject", {
        "database": args.database,
        "name": args.name,
        "namespace": args.namespace,
    }, opts);
}

/**
 * A collection of arguments for invoking getObject.
 */
export interface GetObjectOutputArgs {
    /**
     * Name of the Database
     */
    database: pulumi.Input<string>;
    /**
     * Name of the Object
     */
    name: pulumi.Input<string>;
    /**
     * Name of the Namespace
     */
    namespace: pulumi.Input<string>;
}
