// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * Store resource
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as deltastream from "@deltastream/pulumi";
 *
 * const allStores = deltastream.getStores({});
 * ```
 */
export function getStores(opts?: pulumi.InvokeOptions): Promise<GetStoresResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("deltastream:index/getStores:getStores", {
    }, opts);
}

/**
 * A collection of values returned by getStores.
 */
export interface GetStoresResult {
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    /**
     * List of stores
     */
    readonly items: outputs.GetStoresItem[];
}
/**
 * Store resource
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as deltastream from "@deltastream/pulumi";
 *
 * const allStores = deltastream.getStores({});
 * ```
 */
export function getStoresOutput(opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetStoresResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("deltastream:index/getStores:getStores", {
    }, opts);
}
